services:
  api:
    build: .
    command: python main.py
    volumes:
      - .:/app
      - ../front/dist:/app/front/dist
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
